//
//  SingleFileDownloader.swift
//  PCL.Mac
//
//  Created by YiZhiMCQiu on 2025/8/24.
//  Generated by Copilot GPT-5.
//

import Foundation

public class SingleFileDownloader {
    public static func download(
        task: InstallTask? = nil,
        url: URL,
        destination: URL,
        replaceMethod: ReplaceMethod = .skip,
        networkCategory: NetworkCategory = .gameDownload,
        progress: ((Double) -> Void)? = nil
    ) async throws {
        if FileManager.default.fileExists(atPath: destination.path) && replaceMethod == .skip {
            task?.completeOneFile()
            progress?(1)
            return
        }
        
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.setValue("PCL.Mac/\(SharedConstants.shared.version)", forHTTPHeaderField: "User-Agent")
        
        let delegate = SingleFileDownloadDelegate(
            destination: destination,
            replaceMethod: replaceMethod,
            task: task,
            progress: progress
        )
        let session = URLSession(
            configuration: Requests.makeConfiguration(forceUseProxy: Requests.shouldUseProxy(for: networkCategory)),
            delegate: delegate,
            delegateQueue: nil
        )
        defer {
            session.invalidateAndCancel()
        }

        try await delegate.start(request: request, session: session)
        task?.completeOneFile()
        progress?(1.0)
    }
}

private final class SingleFileDownloadDelegate: NSObject, URLSessionDownloadDelegate {
    private let destination: URL
    private let replaceMethod: ReplaceMethod
    private weak var task: InstallTask?
    private let progress: ((Double) -> Void)?
    private let lock = NSLock()
    private var continuation: CheckedContinuation<Void, Error>?
    private var downloadTask: URLSessionDownloadTask?
    private var finished = false
    private var lastWritten: Int64 = 0

    init(
        destination: URL,
        replaceMethod: ReplaceMethod,
        task: InstallTask?,
        progress: ((Double) -> Void)?
    ) {
        self.destination = destination
        self.replaceMethod = replaceMethod
        self.task = task
        self.progress = progress
    }

    func start(request: URLRequest, session: URLSession) async throws {
        try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                self.lock.lock()
                self.continuation = continuation
                self.lock.unlock()

                let downloadTask = session.downloadTask(with: request)
                self.downloadTask = downloadTask
                downloadTask.resume()
            }
        } onCancel: {
            self.downloadTask?.cancel()
        }
    }

    func urlSession(
        _ session: URLSession,
        downloadTask: URLSessionDownloadTask,
        didWriteData bytesWritten: Int64,
        totalBytesWritten: Int64,
        totalBytesExpectedToWrite: Int64
    ) {
        let delta = totalBytesWritten - lastWritten
        lastWritten = totalBytesWritten
        Task { await SpeedMeter.shared.addBytes(Int(delta)) }

        guard totalBytesExpectedToWrite > 0 else {
            progress?(-1)
            return
        }
        let value = Double(totalBytesWritten) / Double(totalBytesExpectedToWrite)
        Task { @MainActor in
            self.task?.currentStagePercentage = value
            self.progress?(value)
        }
    }

    func urlSession(
        _ session: URLSession,
        downloadTask: URLSessionDownloadTask,
        didFinishDownloadingTo location: URL
    ) {
        do {
            if FileManager.default.fileExists(atPath: destination.path) {
                switch replaceMethod {
                case .replace:
                    try FileManager.default.removeItem(at: destination)
                case .throw:
                    throw MyLocalizedError(reason: "\(destination.lastPathComponent) 已存在。")
                case .skip:
                    break
                }
            } else {
                try FileManager.default.createDirectory(at: destination.parent(), withIntermediateDirectories: true)
            }

            if replaceMethod != .skip || !FileManager.default.fileExists(atPath: destination.path) {
                try FileManager.default.moveItem(at: location, to: destination)
            }
        } catch {
            resumeOnce(with: .failure(error))
        }
    }

    func urlSession(
        _ session: URLSession,
        task: URLSessionTask,
        didCompleteWithError error: Error?
    ) {
        if let error {
            resumeOnce(with: .failure(error))
            return
        }

        if let response = task.response as? HTTPURLResponse,
           !(200..<300).contains(response.statusCode) {
            resumeOnce(with: .failure(MyLocalizedError(reason: "远程服务器返回了 \(response.statusCode)。")))
            return
        }

        resumeOnce(with: .success(()))
    }

    private func resumeOnce(with result: Result<Void, Error>) {
        lock.lock()
        guard !finished else {
            lock.unlock()
            return
        }
        finished = true
        let continuation = continuation
        self.continuation = nil
        lock.unlock()

        switch result {
        case .success:
            continuation?.resume()
        case .failure(let error):
            continuation?.resume(throwing: error)
        }
    }
}
